
services:
  # Servicio web ( Apache + PHP )
  web:
    build: ./docker/php
    container_name: mi_apache_php
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    #Base de datos
  db:
    image: mariadb:lts-ubi10
    container_name: mi_maria_db
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIAD _USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes: 
  db_data:
